config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  resources :comments
end
  #root "posts#index"
  root "pages#about"
  
  get '/about', to: 'pages#about'
  get '/posts', to: 'posts#index'
  get '/chapter1', to: 'pages#chapter1'
  get '/chapter2', to: 'pages#chapter2'
  get '/chapter3', to: 'pages#chapter3'
  get '/chapter4', to: 'pages#chapter4'
  get '/chapter5', to: 'pages#chapter5'
  get '/chapter6', to: 'pages#chapter6'
  get '/chapter7', to: 'pages#chapter7'
  get '/chapter8', to: 'pages#chapter8'
  get '/chapter9', to: 'pages#chapter9'
  get '/chapter10', to: 'pages#chapter10'
  get '/chapter11', to: 'pages#chapter11'
  get '/chapter12', to: 'pages#chapter12'
  get '/chapter13', to: 'pages#chapter13'
  get '/chapter14', to: 'pages#chapter14'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length:{ minimum: 5}
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def chapter1
  end
  
  def chapter2
  end
  
  def chapter3
  end  

  def chapter4
  end  

  def chapter5
  end  

  def chapter6
  end  

  def chapter7
  end  

  def chapter8
  end  

  def chapter9
  end  

  def chapter10
  end  

  def chapter11
  end  

  def chapter12
  end  

  def chapter13
  end  

  def chapter14
  end  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    
    if @post.save
    redirect_to @post
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: 
      {confirm: 'Are you sure?'} %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Copyright &copy; 2017 Mike Dalton; All Rights Reserved.
    </small>
    <nav>
        <ul>
            
        </ul>
    </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MCLA - Java Tutorial</title>
  
<!-- ======================= Google Adsense ============================ -->  
<!--<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5227259389540783",
    enable_page_level_ads: true
  });
</script>-->
<!-- ======================== End Google Adsense ========================-->  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.gogle.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico'%>
  <%= csrf_meta_tags %>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
</head>
<!--<body background="images/bg4.jpg"> -->
<body>
<!-- ========================== Sidebar ======================== --> 
<div>
<!--  <div id="sidebar">
    <ul>
      <li><%= link_to "01 - Programming", chapter1_path %></li>
      <li><%= link_to "02 - Variables", chapter2_path %></li>
      <li><%= link_to "03 - If Statements", chapter3_path %></li>
      <li><%= link_to "04 - Programming Practices", chapter4_path %></li>
      <li><%= link_to "05 - While Loops", chapter5_path %></li>
      <li><%= link_to "06 - For Loops", chapter6_path %></li>
      <li><%= link_to "07 - Arrays", chapter7_path %></li>
      <li><%= link_to "08 - Classes Objects and Methods", chapter8_path %></li>
      <li><%= link_to "09 - Strings", chapter9_path %></li>
      <li><%= link_to "10 - Text Files", chapter10_path %></li>
      <li><%= link_to "11 - Defining Methods", chapter11_path %></li>
      <li><%= link_to "12 - Programming with Methods", chapter12_path %></li>
      <li><%= link_to "13 - Defining Classes", chapter13_path %></li>
      <li><%= link_to "14 - Prorgamming with Classes", chapter14_path %></li>
    </ul>
  </div><!-- sidebar -->
</div>
<!-- ====================== End Sidebar ======================== -->  

<!-- ======================= main content ====================== -->
<div class="container">
  <br/><br/><br/>
  <!--<div class="jumbotron" style="background-color: #DAA520;"> -->
<!--  <div class="jumbotron"> -->
  <% flash.each do |name, msg| %>
    </br></br>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %> 

  <%= yield %>

  <%= render 'layouts/footer' %>
  <!--</div>-->
</div><!-- main_content -->
<!-- ==================== End main content ====================== --> 
<!-- ========================= Menu Bar ========================= --> 
<nav class="navbar navbar-inverse navbar-fixed-top">
<!--<nav class="navbar navbar-inverse">   -->
  <div class="container-fluid">
    <!--<a class="navbar-brand" href="#">MCLA - Java Tutorial</a>-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Main", root_path, class: "navbar-brand" %>
    </div>    
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav"> 
        <li><%= link_to "Posts", posts_path %></li>  
        
        <% if user_signed_in? %>
            <li><%= link_to "Make Post", new_post_path %></li>
        <% end %>
      </ul> 
      
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to " Login", new_user_session_path,class:"glyphicon glyphicon-log-in" %></li>
        <% end %>
  
        <% if user_signed_in? %>
            <li><%= link_to " Logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %></li>
        <% end %>
      </ul>
    </div> <!--end collapse navbar-collapse -->
  </div><!-- end container-fluid -->
</nav>
<!-- ======================End Menu Bar ========================= --> 

</body>
</html>

app/views/layouts/application_nav.html..erb
<!DOCTYPE html>
<html>
<head>
  <title>MCLA - Java Tutorial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.gogle.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico'%>
  <%= csrf_meta_tags %>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
</head>
<body>
<!-- ========================= Sidebar ======================== --> 
  <div id="sidebar">
    <ul>
      <li><%= link_to "01 - Programming", chapter1_path %></li>
      <li><%= link_to "02 - Variables", chapter2_path %></li>
      <li><%= link_to "03 - If Statements", chapter3_path %></li>
      <li><%= link_to "04 - Programming Practices", chapter4_path %></li>
      <li><%= link_to "05 - While Loops", chapter5_path %></li>
      <li><%= link_to "06 - For Loops", chapter6_path %></li>
      <li><%= link_to "07 - Arrays", chapter7_path %></li>
      <li><%= link_to "08 - Classes Objects and Methods", chapter8_path %></li>
      <li><%= link_to "09 - Strings", chapter9_path %></li>
      <li><%= link_to "10 - Text Files", chapter10_path %></li>
      <li><%= link_to "11 - Defining Methods", chapter11_path %></li>
      <li><%= link_to "12 - Programming with Methods", chapter12_path %></li>
      <li><%= link_to "13 - Defining Classes", chapter13_path %></li>
      <li><%= link_to "14 - Prorgamming with Classes", chapter14_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Posts", root_path %></li>
    
    <% if !user_signed_in? %>
      <li><%= link_to "User Login", new_user_session_path %></li>
    <% end %>
    </ul>
      
  </div><!-- sidebar -->
<!-- ====================== End Sidebar ======================== -->  

<!-- ======================= main content ====================== -->
 <div id="main_content"> 
    <div id="header">
      </br></br></br></br>
      <% if current_page?(root_path) %>
        <p>Post Feed</p>
      <% elsif current_page?(about_path) %>
        <p>my Site</p>
      <% else %>
        <%= link_to "Back to Post Feed", root_path %>
      <% end %>
      <% if user_signed_in? %>
        <div class="button">
          <button class="button"><%= link_to "Make Post", new_post_path %></button>
          <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></buton>
        </div>
      <% end %>
      
    </div><!-- header -->

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>

  <%= yield %>
  </div>
<!-- ====================End main content ====================== --> 
<!-- test -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>


</body>
</html>

app/views/layouts/application_testing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MCLA - Java Tutorial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.gogle.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico'%>
  <%= csrf_meta_tags %>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      position: relative;
  }
  ul.nav-pills {
      top: 20px;
      position: fixed;
  }


  </style>  
  
</head>


<div class="container">
  <div class="row">

    <nav class="col-sm-3" id="myScrollspy">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#section1">Section 1</a></li>
        <li><a href="#section2">Section 2</a></li>
        <li><a href="#section3">Section 3</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Section 4 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#section41">Section 4-1</a></li>
            <li><a href="#section42">Section 4-2</a></li>
          </ul>
        </li>
      </ul>
    </nav>

    <div class="col-sm-9">
        <h1>Section 1</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
        <p>
        Source code is code that was typed by a programmer in a high level language like Java. The compiler reads this file, and creates a new file containing executable code that the computer can run. Once a program has been compiled into machine language, it will only run on a processor it was compiled for. A program normally has to be compiled for each type of computer it will run on.

		Java programs are compiled to run on the Java Virtual Machine (JVM). The JVM is an imaginary microprocessor with its own binary instruction set. When we compile our Java programs, they are converted to run on this imaginary processor. A compiled Java program is said to in bytecode format.
		When we run a Java program, the JVM converts the Java bytecode into machine language for computer on which it is will run.

		The JVM is part of the Java Runtime Environment (JRE). The JRE is needed to run Java programs. The JRE contains the JVM and lots of compiled Java files. This software is free, but most operating systems include it so you don't need to install it. When your computer nags you about a Java update, it is trying to install the latest version of the JRE. Since virtually all computers have a JVM, Java programs are platform independent. A compiled Java program will run on any computer.

		To create new Java programs, a developer must install the Java Development Kit (JDK), which is also free and can be found at java.sun.com. There are three editions of the JDK; Java Micro Edition (J2ME), Java Standard Edition (J2SE), and Java Enterprise Edition (J2EE). We will be using the Standard Edition. The JDK is a development kit. Among other things, it contains a program that compiles Java source code.

The JDK includes the JRE, which includes the JVM.
        </p>
        <p>
        Source code is code that was typed by a programmer in a high level language like Java. The compiler reads this file, and creates a new file containing executable code that the computer can run. Once a program has been compiled into machine language, it will only run on a processor it was compiled for. A program normally has to be compiled for each type of computer it will run on.

		Java programs are compiled to run on the Java Virtual Machine (JVM). The JVM is an imaginary microprocessor with its own binary instruction set. When we compile our Java programs, they are converted to run on this imaginary processor. A compiled Java program is said to in bytecode format.
		When we run a Java program, the JVM converts the Java bytecode into machine language for computer on which it is will run.

		The JVM is part of the Java Runtime Environment (JRE). The JRE is needed to run Java programs. The JRE contains the JVM and lots of compiled Java files. This software is free, but most operating systems include it so you don't need to install it. When your computer nags you about a Java update, it is trying to install the latest version of the JRE. Since virtually all computers have a JVM, Java programs are platform independent. A compiled Java program will run on any computer.

		To create new Java programs, a developer must install the Java Development Kit (JDK), which is also free and can be found at java.sun.com. There are three editions of the JDK; Java Micro Edition (J2ME), Java Standard Edition (J2SE), and Java Enterprise Edition (J2EE). We will be using the Standard Edition. The JDK is a development kit. Among other things, it contains a program that compiles Java source code.

The JDK includes the JRE, which includes the JVM.
        </p>
                <p>
		        Source code is code that was typed by a programmer in a high level language like Java. The compiler reads this file, and creates a new file containing executable code that the computer can run. Once a program has been compiled into machine language, it will only run on a processor it was compiled for. A program normally has to be compiled for each type of computer it will run on.

				Java programs are compiled to run on the Java Virtual Machine (JVM). The JVM is an imaginary microprocessor with its own binary instruction set. When we compile our Java programs, they are converted to run on this imaginary processor. A compiled Java program is said to in bytecode format.
				When we run a Java program, the JVM converts the Java bytecode into machine language for computer on which it is will run.

				The JVM is part of the Java Runtime Environment (JRE). The JRE is needed to run Java programs. The JRE contains the JVM and lots of compiled Java files. This software is free, but most operating systems include it so you don't need to install it. When your computer nags you about a Java update, it is trying to install the latest version of the JRE. Since virtually all computers have a JVM, Java programs are platform independent. A compiled Java program will run on any computer.

				To create new Java programs, a developer must install the Java Development Kit (JDK), which is also free and can be found at java.sun.com. There are three editions of the JDK; Java Micro Edition (J2ME), Java Standard Edition (J2SE), and Java Enterprise Edition (J2EE). We will be using the Standard Edition. The JDK is a development kit. Among other things, it contains a program that compiles Java source code.

		The JDK includes the JRE, which includes the JVM.
        </p>
                <p>
		        Source code is code that was typed by a programmer in a high level language like Java. The compiler reads this file, and creates a new file containing executable code that the computer can run. Once a program has been compiled into machine language, it will only run on a processor it was compiled for. A program normally has to be compiled for each type of computer it will run on.

				Java programs are compiled to run on the Java Virtual Machine (JVM). The JVM is an imaginary microprocessor with its own binary instruction set. When we compile our Java programs, they are converted to run on this imaginary processor. A compiled Java program is said to in bytecode format.
				When we run a Java program, the JVM converts the Java bytecode into machine language for computer on which it is will run.

				The JVM is part of the Java Runtime Environment (JRE). The JRE is needed to run Java programs. The JRE contains the JVM and lots of compiled Java files. This software is free, but most operating systems include it so you don't need to install it. When your computer nags you about a Java update, it is trying to install the latest version of the JRE. Since virtually all computers have a JVM, Java programs are platform independent. A compiled Java program will run on any computer.

				To create new Java programs, a developer must install the Java Development Kit (JDK), which is also free and can be found at java.sun.com. There are three editions of the JDK; Java Micro Edition (J2ME), Java Standard Edition (J2SE), and Java Enterprise Edition (J2EE). We will be using the Standard Edition. The JDK is a development kit. Among other things, it contains a program that compiles Java source code.

		The JDK includes the JRE, which includes the JVM.
        </p>
    </div>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>

  <%= yield %>
  </div>
  </div><!-- container -->

</body>
</html>

app/views/pages/GridTemplate.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <h1>Hello World!</h1>
  <p>Resize the browser window to see the effect.</p>
  <div class="row">
    <div class="col-sm-3" style="background-color:lavender;">.col-sm-3</div>
    <div class="col-sm-6" style="background-color:lavenderblush;">.col-sm-6</div>
    <div class="col-sm-3" style="background-color:lavender;">.col-sm-3</div>
  </div>
</div>
<!----------------------------->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3" >
      .col-sm-3
    </div>
    <div class="col-sm-3" >
      .col-sm-6
    </div>
    <div class="col-sm-3" >
      .col-sm-3
    </div>
    <div class="col-sm-3" >
      .col-sm-3
    </div>
  </div>
</div>
<!----------------------------->
</body>
</html>

app/views/pages/GridTemplate2.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <h1>Hello World!</h1>
  <p>Resize the browser window to see the effect.</p>
  <div class="row">
    <div class="col-sm-8" style="background-color:lavender;">.col-sm-8
      <div class="row">
        <div class="col-sm-6" style="background-color:lightcyan;">.col-sm-6</div>
        <div class="col-sm-6" style="background-color:lightgray;">.col-sm-6</div>
      </div>
    </div>
    <div class="col-sm-4" style="background-color:lavenderblush;">.col-sm-4</div>
  </div>
</div>
    
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= render 'shared/errors' %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/posts/edit.html.erb
<!--<div id="page_wrapper">-->
  <h1>Edit Post</h1>
  <%= render 'form' %>
<!--</div>-->

app/views/posts/index.html.erb
</br></br></br>
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length:100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>
      

app/views/posts/new.html.erb
<!-- <div id="page_wrapper"> -->
  <h1>New Post</h1>
  <%= render 'form' %>
<!--</div>-->

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    submitted <%= time_ago_in_words(@post.created_at) %> ago |
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure'} %>
    <% end %>
  </p>
  
  <p clas="body">
    <%= @post.body %>
  </p>
  
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3> Joint Discustion: </h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@post.errors.count, "error" ) %> prohibited this post from being saved:</h2>
          </h2>
          <div class="panel-body">
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %>
              <% end %>              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>